site:
  #build : .
  image: yutamg/laravel:ubuntu
  ports :
   - "9001:80"
  volumes:
   - ./app:/var/www/html/
   - ./apache:/etc/apache2/sites-available
  links:
   - mysql:mysql
 
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "9002:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - mysql:mysql
mysql:
  image: mysql:5.6
  ports:
   - "9003:3306"  
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mysite
    - MYSQL_USER=mysite
    - MYSQL_PASSWORD=password

